site_name: First Six Weeks
site_url: https://14thgalway.github.io/first-six-weeks
theme:
  name: material
nav:
  - Home: index.md
  - Beavers:
    - Week 1 (16/9)  - Meeting: beavers/week1.md
    - Week 2 (23/9)  - Meeting: beavers/week2.md
    - Week 3 (30/9)  - Meeting: beavers/week3.md
    - Week 4 (9+10/10) - Event:   beavers/week4.md
    - Week 5 (14/10) - Meeting: beavers/week5.md
    - Week 6 (30/10) - Event:   beavers/week6.md
    - Week 7 (28/10) - Meeting: beavers/week7.md
  - Cubs:
    - Week 1 (16/9)  - Meeting: cubs/week1.md
    - Week 2 (23/9)  - Meeting: cubs/week2.md
    - Week 3 (30/9)  - Meeting: cubs/week3.md
    - Week 4 (9+10/10) - Event:   cubs/week4.md
    - Week 5 (14/10) - Meeting: cubs/week5.md
    - Week 6 (30/10) - Event:   cubs/week6.md
    - Week 7 (28/10) - Meeting: cubs/week7.md
  - About: about.md
